CREATE DATABASE exportacao;
USE exportacao;
CREATE TABLE exportacao_a_china (
id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT, 
Código_CUCI_Divisao INT(11) NOT NULL, 
Descricao_CUCI_Item varchar(220) NOT NULL, 
UF_do_Produto VARCHAR(200) NOT NULL,
2022_Valor_FOB_US$ INT(11) NOT NULL, 
2021_Valor_FOB_US$ INT(11) NOT NULL, 
2020_Valor_FOB_US$ INT(11) NOT NULL,
2019_Valor_FOB_US$ INT(11) NOT NULL, 
2018_Valor_FOB_US$ INT(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET = utf8;